name: Node.js CI
on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    env:
      PERSON_VERSION: $(node -p "require('./package').version")
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get Version
        uses: battila7/get-version-action@v2.2.1
      - run: echo ${{ steps.get_version.outputs.version }}
      - run: echo ${{ steps.get_version.outputs.version-without-v }}
      - run: docker build . -t beritou/person:${{ env.PERSON_VERSION }}
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/person:${{ env.PERSON_VERSION }}
      - name: akkasls Deploy
        uses: retgits/akkasls-action@v2
        with:
          cmd: "services deploy person ${{ secrets.DOCKERHUB_USERNAME }}/person:${{ steps.get_version.outputs.version }}"
        env:
          token: ${{ secrets.AKKASLS_TOKEN }}
          project: ${{ secrets.AKKASLS_PROJECT_ID }}
